[project]
name = "auth-example1"
version = "0.2.0"
description = "Ejemplo didáctico de login web con FastAPI + Jinja2 (sesiones con cookie)"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "jinja2>=3.1.6",
]

[tool.fastapi]
entrypoint = "main:app"